### ISSUE TITLE
[FEAT] main페이지 CSS 구현

### ISSUE THREAD

**Issue by dvp-tae** [ssu-Recipable/FrontEnd#12]
## 📌 Feature Issue
- 메인 페이지 CSS 구현

## 📝 To-do
- [ ] page/main 생성
- [ ] main.tsx 구현
- [ ] component 단위로 분리
