### ISSUE TITLE
[FEAT] #6 식재료 추가/영수증 업로드 UI 구현

### ISSUE THREAD

**Issue by dvp-tae** [ssu-Recipable/FrontEnd#16]
## 📌 Feature Issue
- 식재료 추가 페이지, 영수증 업로드 페이지 UI 구현

## 📝 To-do
- [x] AddIngredient.tsx 구현
- [ ] ScanReceipt.tsx 구현
- [x] 이미지 업로드 함수 구현
