### ISSUE TITLE
[FEAT] #8 스캔 결과 페이지 UI 구현

### ISSUE THREAD

**Issue by dvp-tae** [ssu-Recipable/FrontEnd#20]
## 📌 Feature Issue
- 스캔 결과 페이지 UI 구현
- 재료 입력 컴포넌트 스타일링

## 📝 To-do
- [ ] 직접 입력 페이지 재료 추가 컴포넌트 부분 스타일링
- [ ] 재료 추가 삭제 기능 구현
- [ ] 스캔 결과 페이지 UI 생성
