### ISSUE TITLE
[API] 마이페이지API작업

### ISSUE THREAD

**Issue by dvp-tae** [ssu-Recipable/FrontEnd#47]
## 📌 Feature Issue
- 마이페이지 API 작업

## 📝 To-do
- [ ] 사용자 정보 가져오기
- [ ] 프로필 수정 구현
- [ ] 회원 탈퇴 기능 구현
