### ISSUE TITLE
[FEAT] 자체로그인구현

### ISSUE THREAD

**Issue by dvp-tae** [ssu-Recipable/FrontEnd#48]
## 📌 Feature Issue
- 자체 이메일 로그인 서비스 구현

## 📝 To-do
- [x] 약관동의 양식 만들기
- [x] 약관동의 체크 박스
- [ ] 약관동의, 회원가입, 로그인 페이지 구현

**Comment by dvp-tae** [comment]
yarn add -D vite-plugin-svgr
SVG 사용을 위해 플러그인 설치

**Comment by dvp-tae** [comment]
yarn add zod react-hook-form @hookform/resolvers
reack-hook-form 라이브러리 설치 및 유효성 검사 라이브러리 zod & zodresolvers 설치
